### ISSUE TITLE
Criar Volume para Tokens

### ISSUE THREAD

**Issue by moskoweb** [wppconnect-team/wpp-docker#1]
Seria bom separar os tokens em um volume para que fique facil de copiar ou fazer backup dos mesmos.

**Comment by bgastaldi** [comment]
Bom dia,

Na verdade se você pegar o vídeo 2 (https://www.youtube.com/watch?v=kDHbf1TWkBw) e trocar o docker-compose.yaml pelo abaixo, você tem o volume compartilhado.

``` bash
wppconnect-server:
    build: 
      context: ./wppconnect-server
      dockerfile: Dockerfile
    image: wppconnect-server
    container_name: wppconnect-server
    hostname: wppconnect-server
    volumes:
      - ./wppconnect-server/app/token:/home/node/app/token
      - ./wppconnect-server/app:/home/node/app
      - /home/node/app/node_modules
    entrypoint: docker-entrypoint.sh yarn dev
    networks: 
      - wpp-network
    tty: true
$ docker-compose up --build
```

Não me recordo se o caminho é **/home/node/app/token** ou simplesmente **/home/token**.
De toda forma também estamos vendo para implantar o firebase/mongo e também excluir essas no endpoint **close**.
