### ISSUE TITLE
nodemon inside docker server?

### ISSUE THREAD

**Issue by jrvidotti** [wppconnect-team/wpp-docker#5]
Na minha opinião, o entrypoint deve ser configurado para executar usando node ou outra solução para modo produção, e não nodemon.

Outra questão é que o docker server continuar rodando mesmo quando o código QR não foi lido, concordam?

![image](https://user-images.githubusercontent.com/5623041/141333471-8cf6b683-a0e2-4f26-94fa-f297869bec24.png)

**Comment by bgastaldi** [comment]
Opa, desculpa a demora.
Manda um PR pra gente
